### ISSUE TITLE
what is mscnn？

### ISSUE THREAD

**Issue by zqdeepbluesky** [yougoforward/TFFRCNNwithmscnn#1]
hi，thanks for your work ,I just don't know mscnn means what,can you tell me about it?thanks so much.

**Comment by yougoforward** [comment]
mscnn refers to network proposed in paper "A Unified Multi-scale Deep Convolutional Neural Network for Fast Object Detection", and it is originally realized in caffe. Once I want to realize it based on TFFRCNN repository, but at last I give up and perform experiments in caffe. So I'm sorry to make you confused with this repository and I will delete it soon.

**Comment by zqdeepbluesky** [comment]
thanks for your reply.good luck.
